ALTER TABLE public.tools
  ADD COLUMN IF NOT EXISTS logo_color TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS votes INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS api_available BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS free_plan BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS open_source BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS pricing TEXT,
  ADD COLUMN IF NOT EXISTS automation TEXT,
  ADD COLUMN IF NOT EXISTS community TEXT,
  ADD COLUMN IF NOT EXISTS models TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS features TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS ai_capabilities TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS use_cases TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_tools_votes ON public.tools(votes DESC);
CREATE INDEX IF NOT EXISTS idx_tools_featured ON public.tools(featured);
